"use client";

import { useEffect, useMemo, useState } from "react";
import { calculateEstimatorPrice, type PricingDesignLevel, type PricingProjectType } from "@/lib/estimator-pricing";

type ProjectType = PricingProjectType;
type DesignLevel = PricingDesignLevel;
type Condition = "Lahan kosong" | "Persiapan pembangunan" | "Bangunan existing" | "Sebagian direnovasi" | "Renovasi total";
type Timeline = "Segera" | "1–3 bulan" | "3–6 bulan" | ">6 bulan" | "Masih eksplorasi";
type EstimatorSettings = { basic_rate:number; essential_rate:number; signature_rate:number; premium_rate:number; rumah_baru_multiplier:number; renovasi_multiplier:number; villa_multiplier:number; commercial_multiplier:number; min_range_multiplier:number; max_range_multiplier:number; min_area:number };
const FALLBACK_SETTINGS:EstimatorSettings={basic_rate:22500,essential_rate:40000,signature_rate:62500,premium_rate:100000,rumah_baru_multiplier:1,renovasi_multiplier:1.15,villa_multiplier:1.2,commercial_multiplier:1.3,min_range_multiplier:.85,max_range_multiplier:1.25,min_area:20};
const PROJECT_LABELS:Record<ProjectType,string>={"Rumah Baru":"Rumah Baru",Renovasi:"Renovasi",Villa:"Villa",Commercial:"Ruang Usaha"};
const DESIGN_LABELS:Record<DesignLevel,string>={Basic:"Basic",Essential:"Essential",Signature:"Signature",Premium:"Premium",Custom:"Custom"};
const DESIGN_DESCRIPTIONS:Record<DesignLevel,string>={Basic:"Mulai dari prarencana dan kebutuhan dasar.",Essential:"Desain rumah dasar yang efisien dan terarah.",Signature:"Desain lebih lengkap, personal, dan berkembang.",Premium:"Dokumen dan pengembangan desain lebih menyeluruh.",Custom:"Proyek khusus diarahkan ke konsultasi dan proposal."};
const NEED_OPTIONS=["Konsep & denah","Desain arsitektur","Desain interior","Desain fasad","Visualisasi 3D","Gambar kerja","Perencanaan ruang","Renovasi & pengembangan","Paket desain lengkap"] as const;
export const ESTIMATOR_LEAD_CONTEXT_KEY="rumah-arsitek-estimator-lead-context-v1";
function formatRupiah(value:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value)}
function sanitizeArea(value:number,minimum:number){if(!Number.isFinite(value))return minimum;return Math.max(minimum,Math.min(10000,Math.round(value)))}
export default function ArchitectureEstimator(){
 const [step,setStep]=useState(1),[projectType,setProjectType]=useState<ProjectType>("Rumah Baru"),[designLevel,setDesignLevel]=useState<DesignLevel>("Signature"),[area,setArea]=useState(FALLBACK_SETTINGS.min_area),[landArea,setLandArea]=useState(""),[floors,setFloors]=useState("1"),[condition,setCondition]=useState<Condition>("Lahan kosong"),[needs,setNeeds]=useState<string[]>(["Desain arsitektur"]),[city,setCity]=useState(""),[province,setProvince]=useState(""),[timeline,setTimeline]=useState<Timeline>("1–3 bulan"),[settings,setSettings]=useState<EstimatorSettings>(FALLBACK_SETTINGS),[loadingSettings,setLoadingSettings]=useState(true);
 useEffect(()=>{let mounted=true;(async()=>{try{const r=await fetch("/api/estimator",{cache:"no-store"});if(!r.ok)throw new Error("Gagal mengambil estimator settings");const x=await r.json();if(mounted&&x?.settings)setSettings({basic_rate:Number(x.settings.basic_rate),essential_rate:Number(x.settings.essential_rate),signature_rate:Number(x.settings.signature_rate),premium_rate:Number(x.settings.premium_rate),rumah_baru_multiplier:Number(x.settings.rumah_baru_multiplier),renovasi_multiplier:Number(x.settings.renovasi_multiplier),villa_multiplier:Number(x.settings.villa_multiplier),commercial_multiplier:Number(x.settings.commercial_multiplier),min_range_multiplier:Number(x.settings.min_range_multiplier),max_range_multiplier:Number(x.settings.max_range_multiplier),min_area:Number(x.settings.min_area)})}catch(e){console.error("[ESTIMATOR SETTINGS]",e)}finally{if(mounted)setLoadingSettings(false)}})();return()=>{mounted=false}},[]);
 useEffect(()=>{if(area<settings.min_area||!Number.isFinite(area))setArea(settings.min_area)},[settings.min_area,area]);
 useEffect(()=>{if(projectType==="Rumah Baru"&&condition!=="Lahan kosong"&&condition!=="Persiapan pembangunan"&&condition!=="Bangunan existing")setCondition("Lahan kosong");if(projectType!=="Rumah Baru"&&(condition==="Lahan kosong"||condition==="Persiapan pembangunan"))setCondition("Bangunan existing")},[projectType,condition]);
 const calculation=useMemo(()=>calculateEstimatorPrice({area:sanitizeArea(area,settings.min_area),projectType,designLevel,floors:Number(floors)||1,condition,needs,landArea:landArea?Number(landArea):null,minArea:settings.min_area,baseRates:{Basic:settings.basic_rate,Essential:settings.essential_rate,Signature:settings.signature_rate,Premium:settings.premium_rate,Custom:0},projectMultipliers:{"Rumah Baru":settings.rumah_baru_multiplier,Renovasi:settings.renovasi_multiplier,Villa:settings.villa_multiplier,Commercial:settings.commercial_multiplier},minRangeMultiplier:settings.min_range_multiplier,maxRangeMultiplier:settings.max_range_multiplier}),[area,designLevel,projectType,floors,condition,needs,landArea,settings]);
 const canNext=()=>step===2?calculation.area>=settings.min_area:step===3?needs.length>0:step===5?!!city.trim()&&!!province.trim():true;
 const toggleNeed=(v:string)=>setNeeds(c=>c.includes(v)?c.filter(x=>x!==v):[...c,v]);
 const continueToConsultation=()=>{try{sessionStorage.setItem(ESTIMATOR_LEAD_CONTEXT_KEY,JSON.stringify({projectType,designLevel,area:calculation.area,estimatedMin:calculation.isCustom?null:Math.round(calculation.min),estimatedMax:calculation.isCustom?null:Math.round(calculation.max),landArea:landArea?Number(landArea):null,floors:Number(floors)||1,condition,needs,city:city.trim(),province:province.trim(),timeline}))}catch(e){console.error("[ESTIMATOR LEAD CONTEXT]",e)}window.location.href="/contact"};
 const conditionOptions=projectType==="Rumah Baru"?["Lahan kosong","Persiapan pembangunan","Bangunan existing"]:["Bangunan existing","Sebagian direnovasi","Renovasi total"];
 return <section id="estimator" className="relative overflow-hidden bg-[#f4efe5] py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><div className="mb-5 inline-flex rounded-full border border-black/10 bg-white/80 px-4 py-2 text-xs font-semibold uppercase tracking-[0.18em] text-[#3f3f3f]">Project Planning Estimator</div><h2 className="max-w-xl font-serif text-4xl leading-[1.05] tracking-[-0.03em] text-black sm:text-5xl">Rencanakan proyek<span className="block text-[#454545]">sebelum melangkah.</span></h2><p className="mt-6 max-w-xl text-base leading-7 text-[#3f3f3f]">Jawab beberapa pertanyaan sederhana untuk mendapatkan gambaran awal investasi desain sekaligus merangkum kebutuhan proyek Anda.</p><div className="mt-8 rounded-2xl border border-black/10 bg-white/70 p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#4a4a4a]">Yang akan Anda dapatkan</p><ul className="mt-3 space-y-2 text-sm leading-6 text-[#444]"><li>• Kisaran estimasi investasi desain</li><li>• Ringkasan kebutuhan proyek</li><li>• Brief yang bisa langsung dikonsultasikan</li></ul></div></div>
 <div className="rounded-3xl border border-black/10 bg-white p-5 shadow-[0_20px_70px_rgba(0,0,0,0.08)] sm:p-7"><div className="mb-6 flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#255c45]">Langkah {step} dari 6</p><p className="mt-1 text-sm text-[#666]">{step===6?"Periksa kembali brief Anda":"Isi sesuai gambaran yang Anda miliki"}</p></div><div className="flex gap-1" aria-hidden="true">{[1,2,3,4,5,6].map(i=><span key={i} className={`h-1.5 w-6 rounded-full ${i<=step?"bg-[#255c45]":"bg-black/10"}`}/>)}</div></div>
 {step===1&&<div><h3 className="text-2xl font-semibold">Apa yang ingin Anda wujudkan?</h3><p className="mt-2 text-sm leading-6 text-[#666]">Pilih jenis proyek yang paling mendekati kebutuhan Anda.</p><div className="mt-6 grid grid-cols-2 gap-3">{(Object.keys(PROJECT_LABELS) as ProjectType[]).map(t=><button key={t} type="button" onClick={()=>setProjectType(t)} className={`rounded-2xl border p-4 text-left transition ${projectType===t?"border-black bg-black text-white":"border-black/10 hover:border-black/30"}`}><span className="text-sm font-semibold">{PROJECT_LABELS[t]}</span><span className="mt-1 block text-xs opacity-70">{t==="Commercial"?"Kantor, cafe, toko, klinik, dan lainnya":t}</span></button>)}</div></div>}
 {step===2&&<div><h3 className="text-2xl font-semibold">Ukuran & kondisi proyek</h3><div className="mt-6 space-y-6"><div><div className="flex items-center justify-between"><label htmlFor="estimator-area" className="text-sm font-semibold">Luas bangunan</label><span className="text-sm font-bold">{calculation.area} m²</span></div><div className="mt-3 flex items-center gap-3"><input id="estimator-area" type="range" min={settings.min_area} max="1000" step="5" value={Math.min(1000,calculation.area)} onChange={e=>setArea(Number(e.target.value))} className="w-full accent-[#255c45]"/><input type="number" min={settings.min_area} value={area} onChange={e=>setArea(Number(e.target.value))} className="w-24 rounded-xl border border-black/10 px-3 py-2 text-center text-sm font-semibold outline-none"/></div><p className="mt-2 text-xs text-[#666]">Minimum {settings.min_area} m².</p></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Luas tanah <span className="font-normal text-[#888]">(opsional)</span><input type="number" min="1" value={landArea} onChange={e=>setLandArea(e.target.value)} placeholder="Contoh 180" className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3 font-normal outline-none"/></label><label className="text-sm font-semibold">Jumlah lantai<select value={floors} onChange={e=>setFloors(e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3 font-normal outline-none"><option value="1">1 lantai</option><option value="2">2 lantai</option><option value="3">3 lantai</option><option value="4">4+ lantai</option></select></label></div><label className="block text-sm font-semibold">Kondisi proyek<select value={condition} onChange={e=>setCondition(e.target.value as Condition)} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3 font-normal outline-none">{conditionOptions.map(i=><option key={i}>{i}</option>)}</select></label></div></div>}
 {step===3&&<div><h3 className="text-2xl font-semibold">Apa yang Anda butuhkan?</h3><p className="mt-2 text-sm leading-6 text-[#666]">Boleh pilih lebih dari satu. Data ini membantu menyiapkan brief dan matching profesional.</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{NEED_OPTIONS.map(i=><button key={i} type="button" onClick={()=>toggleNeed(i)} className={`rounded-xl border px-4 py-3 text-left text-sm font-semibold transition ${needs.includes(i)?"border-[#255c45] bg-[#255c45] text-white":"border-black/10 hover:border-black/30"}`}>{needs.includes(i)?"✓ ":""}{i}</button>)}</div></div>}
 {step===4&&<div><h3 className="text-2xl font-semibold">Pilih level layanan</h3><p className="mt-2 text-sm leading-6 text-[#666]">Level menentukan kedalaman layanan. Custom tidak memakai rate otomatis.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(Object.keys(DESIGN_LABELS) as DesignLevel[]).map(l=><button key={l} type="button" onClick={()=>setDesignLevel(l)} className={`rounded-2xl border p-5 text-left transition ${designLevel===l?"border-[#255c45] bg-[#255c45] text-white":"border-black/10 hover:border-black/30"}`}><span className="font-semibold">{DESIGN_LABELS[l]}{l==="Signature"?" ⭐":""}</span><span className="mt-2 block text-xs leading-5 opacity-75">{DESIGN_DESCRIPTIONS[l]}</span></button>)}</div><div className="mt-5 rounded-xl border border-black/10 bg-[#faf9f6] p-4 text-xs leading-5 text-[#666]">Basic: mulai Rp15–30k/m² · Essential: Rp30–50k/m² · Signature: Rp50–75k/m² · Premium: Rp75–125k/m²+ · Custom: proposal.</div></div>}
 {step===5&&<div><h3 className="text-2xl font-semibold">Lokasi & rencana mulai</h3><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Kota / Kabupaten<input value={city} onChange={e=>setCity(e.target.value)} placeholder="Contoh Kediri" className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3 font-normal outline-none"/></label><label className="text-sm font-semibold">Provinsi<input value={province} onChange={e=>setProvince(e.target.value)} placeholder="Contoh Jawa Timur" className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3 font-normal outline-none"/></label></div><div className="mt-6"><span className="text-sm font-semibold">Kapan Anda berencana memulai?</span><div className="mt-3 grid gap-2 sm:grid-cols-2">{["Segera","1–3 bulan","3–6 bulan",">6 bulan","Masih eksplorasi"].map(i=><button key={i} type="button" onClick={()=>setTimeline(i as Timeline)} className={`rounded-xl border px-4 py-3 text-left text-sm font-semibold ${timeline===i?"border-black bg-black text-white":"border-black/10 hover:border-black/30"}`}>{i}</button>)}</div></div></div>}
 {step===6&&<div><h3 className="text-2xl font-semibold">Review rencana proyek</h3><div className="mt-6 grid gap-3 sm:grid-cols-2">{[["Proyek",PROJECT_LABELS[projectType]],["Luas bangunan",`${calculation.area} m²`],["Luas tanah",landArea?`${landArea} m²`:"Belum diisi"],["Lantai",`${floors==="4"?"4+":floors} lantai`],["Kondisi",condition],["Paket",DESIGN_LABELS[designLevel]],["Lokasi",city&&province?`${city}, ${province}`:"Belum lengkap"],["Mulai",timeline]].map(([l,v])=><div key={l} className="rounded-xl border border-black/10 bg-[#faf9f6] p-4"><span className="text-xs text-[#777]">{l}</span><p className="mt-1 text-sm font-semibold">{v}</p></div>)}</div><div className="mt-3 rounded-xl border border-black/10 bg-[#faf9f6] p-4"><span className="text-xs text-[#777]">Kebutuhan</span><p className="mt-1 text-sm font-semibold">{needs.join(" · ")}</p></div>{calculation.isCustom?<div className="mt-6 rounded-2xl bg-black p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-white/80">Custom project</p><p className="mt-3 text-xl font-bold sm:text-2xl">Estimasi disiapkan melalui konsultasi</p><p className="mt-3 text-sm leading-6 text-white/70">Custom tidak dihitung otomatis per m². Tim RUMAH ARSITEK akan memahami kebutuhan proyek dan menyiapkan arahan proposal sesuai scope.</p></div>:<div className="mt-6 rounded-2xl bg-black p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-white/80">Perkiraan investasi desain</p><div className="mt-3 text-3xl font-bold sm:text-4xl">{formatRupiah(calculation.min)}</div><div className="my-1 text-sm text-white/60">sampai</div><div className="text-3xl font-bold sm:text-4xl">{formatRupiah(calculation.max)}</div><p className="mt-5 border-t border-white/10 pt-4 text-xs leading-5 text-white/70">Estimasi indikatif berdasarkan luas, jenis proyek, level layanan, scope kebutuhan, kondisi, jumlah lantai, dan kompleksitas. Bukan quotation final.</p></div>}</div>}
 <div className="mt-8 flex flex-col gap-3 border-t border-black/10 pt-5 sm:flex-row sm:items-center sm:justify-between"><button type="button" onClick={()=>setStep(s=>Math.max(1,s-1))} disabled={step===1} className="min-h-12 rounded-xl border border-black/10 px-5 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-30">← Kembali</button>{step<6?<button type="button" onClick={()=>{if(canNext())setStep(s=>Math.min(6,s+1))}} disabled={!canNext()} className="min-h-12 rounded-xl bg-[#255c45] px-6 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Lanjut →</button>:<button type="button" onClick={continueToConsultation} className="min-h-12 flex-1 rounded-xl bg-[#255c45] px-6 text-sm font-bold text-white sm:max-w-md">{calculation.isCustom?"Konsultasikan proyek →":"Konsultasikan estimasi ini →"}</button>}</div>{loadingSettings&&<p className="mt-4 text-center text-xs text-[#777]">Memuat konfigurasi estimasi...</p>}</div></div></div></section>;
}
